### PR TITLE
Don't add parenthesis in RawQuery

### PR DESCRIPTION
**Pull request by RangelReale**
By [this change comment](https://github.com/stephenafamo/bob/pull/78#issuecomment-1715792764)

### CODE REVIEW

**Comment by stephenafamo** [comment]
While removing the parenthesis may help with readability, since the queries remain correct, I'll rather leave them in.

In many cases, Bob errs on the side of correctness over readability. While the `NoGroup` parameter is a small change, it will end up being something that has to be maintained indefinitely and edge cases may crop up.

Also, `RawQuery` is expected to be used for FULL queries e.g. (SELECT * FROM users). For raw query fragments, it is `psql.Raw()` that should be used. That does not add any parenthesis.

**Comment by RangelReale** [comment]
`psql.Raw` also seems to add parenthesis:

```go
psql.Select(
  sm.Columns("id", "name"),
  sm.From("users"),
  sm.Where(psql.Raw(`id = 1`)),
)
```

```
SELECT 
id, name
FROM users
WHERE (id = 1)
```

Stepping in the code, it seems somehow this Where with Raw ends up in `expr.group.WriteSQL` which does end up adding parenthesis, I was not able to quickly find out where this `group` came from.

**Comment by stephenafamo** [comment]
I'll take a look and figure out where it comes from.

**Comment by RangelReale** [comment]
This also happens when using `psql.Raw` in Limit and Offset:

```go
		sm.Limit(psql.Raw(`?`, 10)),
		sm.Offset(psql.Raw(`?`, 11)),
```

```
LIMIT ($3)
OFFSET ($4)
```

this example don't make much sense in this way, but in my case I'm using `Raw` to set an sqlx named parameter. This probably will affect other uses of `Raw`.

**Pull request closed without merging**
