### PR TITLE
Add additional methods hook

### PR DESCRIPTION
**Pull request by raphaelvigee**
ref #34

### CODE REVIEW

**Comment by stephenafamo** [comment]
Is this hook necessary? One can just define the methods in the additional templates and they will be rendered at the end of the file.

**Comment by raphaelvigee** [comment]
Oh really ? But how do you tell which file it will end up in ?

**Comment by raphaelvigee** [comment]
Also can confirm, extra stuff in the template ends up being in another file in the generated directory (in my case `gen/template/<model>.go`)
So i would say yes, required?!

**Comment by stephenafamo** [comment]
The directory of the templates should be like this

```
templates/
|-- singleton/
|-- singleton/somthing.go.tpl 
|-- another.go.tpl
```

Files in singleton (e.g. `something.go.tpl`) are run once and generated as-is.  
Files in the root directory(e.g. `another.go.tpl`) are run for each table/view and appended to `model.go`

If you look in `gen/templates` you can see the structure.

Note, if you're using `embed`, it will add the name of the directory to the templates which sometimes messes with how they are interpreted which is why if you look in [`templates.go`](https://github.com/stephenafamo/bob/blob/main/gen/templates.go#LL33-L39C2) you see that I use `fs.Sub` to change the root of the `embed.Fs`

**Comment by raphaelvigee** [comment]
Right got it, not required then, thx!

**Pull request closed without merging**
