### PR TITLE
Fixes for window functions

### LINKED ISSUE #185: [psql] Issues with window functions
The `window` argument to `Function.Over` is unused. 
https://github.com/stephenafamo/bob/blob/main/dialect/psql/dialect/function.go#L76

Additionally, `OVER ()` with an empty window definition is a valid statement, at least for PostgreSQL but is currently not possible due to `wr.def.Valid()` 
https://github.com/stephenafamo/bob/blob/main/dialect/psql/dialect/function.go#L122

### PR DESCRIPTION
**Pull request by relvacode**
Fixes #185

### CODE REVIEW

**Comment by stephenafamo** [comment]
Thank you so much for the PR. 

Can you add a test that uses a window function here?  
https://github.com/stephenafamo/bob/blob/main/dialect/psql/select_test.go

Also run `go generate` after to add it to the examples in the documentation.

**Comment by relvacode** [comment]
Added, let me know if anything else needs changing

**Comment by stephenafamo** [comment]
All looking good 👍🏾 

I also remembered by that argument was included, it was to support [this form of window functions `OVER window_name`](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS)

Would it be possible to support that with your changes?

**Comment by stephenafamo** [comment]
Also, if `Valid()` is now unnecessary, kindly delete it.

**Comment by relvacode** [comment]
Updated. Looks like `.From()` was already there to specify a named window.

**Comment by stephenafamo** [comment]
Thanks for this PR.

I will later make some additional changes to properly construct `OVER window_name` window functions.

**Pull request merged**
